### ISSUE TITLE
Publish new MK1 parts files to RC branch

### ISSUE THREAD

**Issue by 3dGriff** [Hooklet3d/OdinOne#49]
MK1 .STL file upload and verify

**Comment by 3dGriff** [comment]
Frame parts uploaded, testing in progress.  Will upload movement parts tonight.

**Comment by 3dGriff** [comment]
@BotleHewer Movement parts uploaded, haven't been verified.  See commit 1d807f1ef57e300578d9627bf163a5b4cb9b5bb0 for details.

**Comment by BotleHewer** [comment]
@3dGriff working on s3d verification now.

**Comment by BotleHewer** [comment]
Note: Controller_permMountable.v2.stl not verified at this time because it is being reworked to add snap/latch to lid

Report: Part Slicer check
All parts sliced with
PETG $19/1kg
0.2mm Layer Height
3 perimeters
4 top
4 bottom
35% infill
Def Print Speed: 3200 mm/min (53mm/sec)
3 skirt outlines with 4mm offset

---

BedSkate_Set_MK1.stl

supports needed: possibly	
Visual inspection: Cleared
Est material cost/print time: $0.98 / 3.5hrs



UniCap_Idle_MK1.stl

supports needed: yes	
Visual inspection: Cleared
Est material cost/print time: $3.23 / 11.25hrs



UniCap_NEMA_MK1.stl

supports needed: yes
Visual inspection: Cleared
Est material cost/print time: $3.17 / 11hrs



XIdle_Back_MK1.stl

supports needed: yes
Visual inspection: Cleared
Est material cost/print time: $0.31 / 1.25hrs



XSkate_MK1.stl

supports needed: no
Visual inspection: Cleared
Est material cost/print time: $0.69 / 2.5hrs



YIdle_Mount_MK1.stl

supports needed: no
Visual inspection: Cleared
Est material cost/print time: $0.19 / 1hrs

**Comment by 3dGriff** [comment]
Issue closed
